updated

diff --git a/.github/workflows/01-building-blocks.yml b/.github/workflows/01-building-blocks.yml
--- a/.github/workflows/01-building-blocks.yml
+++ b/.github/workflows/01-building-blocks.yml
@@ -8,15 +8,15 @@ jobs:
         steps:
             - name: Say hello
               run: echo " Hello world!"
-    echo-goodbye:
-        runs-on: ubuntu-latest
-        steps:
-            - name: Failed step
-              run: |
-                echo " I will fail"
-                exit 1
-            - name: Say goodbye
-              run: echo "Goodbye!"
+    # echo-goodbye:
+    #     runs-on: ubuntu-latest
+    #     steps:
+    #         - name: Failed step
+    #           run: |
+    #             echo " I will fail"
+    #             exit 1
+    #         - name: Say goodbye
+    #           run: echo "Goodbye!"
     
 
 
